### ISSUE TITLE
完成 boolen integer real char 字面量的 ast 生成和中间代码生成

### ISSUE THREAD

**Issue by Adam-Teng** [Adam-Teng/compiler#12]
仿照 string 字面量的处理方式，注意 C++ 构造函数的设计

**Comment by Laokashouji** [comment]
比如bool类型节点, 应该完成的代码是这样的吗
还是值应该是std::string val呢

以及代码生成部分是否需要修改
```
struct BoolenNode : public ConstValueNode {
 public:
  std::bool val;

  BoolNode(const bool val) : val(val){
    type = std::make_shared<SimpleTypeNode>(Type::BOOLEN);
  }

  llvm::Value *codegen(CodegenContext &context) override;

 protected:
  std::string json_head() const override { return std::string{"\"type\": \"Boolen\", \"value\": \""} + val == true ? "true" : "false" + "\""; }
};
```

**Comment by Adam-Teng** [comment]
> 比如bool类型节点, 应该完成的代码是这样的吗 还是值应该是std::string val呢
> 
> 以及代码生成部分是否需要修改
> 
> ```
> struct BoolenNode : public ConstValueNode {
>  public:
>   std::bool val;
> 
>   BoolNode(const bool val) : val(val){
>     type = std::make_shared<SimpleTypeNode>(Type::BOOLEN);
>   }
> 
>   llvm::Value *codegen(CodegenContext &context) override;
> 
>  protected:
>   std::string json_head() const override { return std::string{"\"type\": \"Boolen\", \"value\": \""} + val == true ? "true" : "false" + "\""; }
> };
> ```

是这样，代码生成部分需要改
