### ISSUE TITLE
解析if case repeat while for 语句

### ISSUE THREAD

**Issue by Adam-Teng** [Adam-Teng/compiler#18]

**Comment by Adam-Teng** [comment]
case 语句需要提前定义 case 表达式类

**Comment by Adam-Teng** [comment]
写代码生成部分的时候需要多看几遍 LLVM 相关文档，对中间代码相关的东西要熟悉

**Comment by fishtwoyuan** [comment]
1

**Comment by fishtwoyuan** [comment]
controlflow里的没有for的例子，我加上吗

**Comment by fishtwoyuan** [comment]
src/ast.hpp [10ms]
:src/parse.y [1ms]
写完后这两个文件冲突，没法合并，暂时没有别的编译错误

**Comment by fishtwoyuan** [comment]
代码生成部分我还得再琢磨琢磨，写不太明白

**Comment by Adam-Teng** [comment]
> src/ast.hpp [10ms] :src/parse.y [1ms] 写完后这两个文件冲突，没法合并，暂时没有别的编译错误

与具体代码无关的东西不要评论

**Comment by Adam-Teng** [comment]
#34 的后续呢，要是这周末没有后续就关 PR 了
