### ISSUE TITLE
关于测试和错误

### ISSUE THREAD

**Issue by fishtwoyuan** [Adam-Teng/compiler#42]
数组越界的错误类型编译运行无法识别，未定义的变量名可识别，非法的变量名可识别

**Comment by fishtwoyuan** [comment]
关于函数参数的传地址，是不是没有实现呢

**Comment by fishtwoyuan** [comment]
关于integer类型溢出的问题，需要做错误处理吗，虽然我感觉不需要

**Comment by Adam-Teng** [comment]
现在代码里有错想改也没工夫改了，有错误的部分测试用例尽量避免一下吧
