### ISSUE TITLE
解析数组

### ISSUE THREAD

**Issue by Adam-Teng** [Adam-Teng/compiler#5]
对着文法对应部分抄，注意需要额外添加关于引用的处理，符号表和表达式相关的地方也需要注意添加数组后带来的变化
- [ ] 词法语法分析
- [ ] ast 定义
- [ ] 符号表补充
- [ ] 补充数组引用相关
- [ ] 由于添加数组带动的其他部分的修改

**Comment by Adam-Teng** [comment]
> 文法对应部分是指哪里呢，另外关于数组的词法和语法分析部分需要完成吗

飞书文档有，不用

**Comment by Laokashouji** [comment]
> <array_type_decl> ::= "array" "[" <array_range> "]" "of" <type_decl>
<array_range> ::= <INTEGER> ".." <INTEGER> | <ID> ".." <ID>

我看文档中没考虑多维数组以及字符作为数组下标等情况，是不是要加一下

**Comment by Adam-Teng** [comment]
> > <array_type_decl> ::= "array" "[" <array_range> "]" "of" <type_decl>
> > <array_range> ::=  ".."  |  ".."
> 
> 我看文档中没考虑多维数组以及字符作为数组下标等情况，是不是要加一下

不用加，就一维就行，这课设最终目标是把快排跑过

**Comment by Adam-Teng** [comment]
#29 的后续呢，要是这周末没有后续就关 PR 了
